package com.example.chudadi.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Immutable
data class ChuButtonPalette(
    val primaryGradient: List<Color>,
    val primaryBorder: Color,
    val secondaryBg: Color,
    val secondaryBorder: Color,
    val ghostBg: Color,
    val ghostBorder: Color,
    val dangerBg: Color,
    val dangerBorder: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textDisabled: Color,
    val primaryShadow: Dp,
    val secondaryShadow: Dp,
    val ghostShadow: Dp,
    val dangerShadow: Dp,
)

@Immutable
data class ChuUiPalette(
    val outer: Color,
    val card: Color,
    val cardBorder: Color,
    val cardShadow: Dp,
    val section: Color,
    val sectionBorder: Color,
    val sectionShadow: Dp,
    val row: Color,
    val rowBorder: Color,
    val input: Color,
    val inputBorder: Color,
    val inputBorderFocused: Color,
    val divider: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val goldAccent: Color,
    val goldHighlight: Color,
    val avatarBg: Color,
    val avatarBorder: Color,
    val success: Color,
    val warning: Color,
    val error: Color,
    val disabled: Color,
    val leftPanelStart: Color,
    val leftPanelEnd: Color,
    val iconTile: Color,
    val subtleGlow: Color,
    val baopeiRow: Color,
    val baopeiBorder: Color,
    val baopeiTag: Color,
    val rankSilver: Color,
    val rankBronze: Color,
    val button: ChuButtonPalette,
)

val ClassicChuUiPalette = ChuUiPalette(
    outer = Color(0xFF1A1008),
    card = Color(0xFF241912),
    cardBorder = Color(0x44C8A96A),
    cardShadow = 24.dp,
    section = Color(0x22C8A96A),
    sectionBorder = Color(0x33C8A96A),
    sectionShadow = 4.dp,
    row = Color(0xAA1D1A14),
    rowBorder = Color(0x44C8A96A),
    input = Color(0xFF1A1208),
    inputBorder = Color(0x55C8A96A),
    inputBorderFocused = Color(0xAABA8C43),
    divider = Color(0x33C8A96A),
    textPrimary = Color(0xFFF7F1E4),
    textSecondary = Color(0xFFB8A882),
    textMuted = Color(0xFF7A6A50),
    goldAccent = Color(0xFFD4A85A),
    goldHighlight = Color(0x44FFE8A0),
    avatarBg = Color(0xFF3A2A1A),
    avatarBorder = Color(0x88F7E8C2),
    success = Color(0xFF81C784),
    warning = Color(0xFFFF9800),
    error = Color(0xFFE57373),
    disabled = Color(0xFF6B6050),
    leftPanelStart = Color(0xFF2A1A08),
    leftPanelEnd = Color(0xFF1A1008),
    iconTile = Color(0x33C8A96A),
    subtleGlow = Color(0x20D4A85A),
    baopeiRow = Color(0x44E07070),
    baopeiBorder = Color(0xAAE07070),
    baopeiTag = Color(0x33E07070),
    rankSilver = Color(0xFF94A3B8),
    rankBronze = Color(0xFFCD7F32),
    button = ChuButtonPalette(
        primaryGradient = listOf(Color(0xFFD4A85A), Color(0xFFBA8C43), Color(0xFF8A6020)),
        primaryBorder = Color(0x44FFE8A0),
        secondaryBg = Color(0xCC1D1A19),
        secondaryBorder = Color(0x66F7E8C2),
        ghostBg = Color(0x18C8A96A),
        ghostBorder = Color(0x44C8A96A),
        dangerBg = Color(0xCC3A1010),
        dangerBorder = Color(0x88E05050),
        textPrimary = Color(0xFFFDF7EA),
        textSecondary = Color(0xFFD6C9A8),
        textDisabled = Color(0xFF6B6050),
        primaryShadow = 6.dp,
        secondaryShadow = 4.dp,
        ghostShadow = 2.dp,
        dangerShadow = 4.dp,
    ),
)

val NightChuUiPalette = ChuUiPalette(
    outer = Color(0xFF070A10),
    card = Color(0xFF111720),
    cardBorder = Color(0x99B8914A),
    cardShadow = 8.dp,
    section = Color(0xFF151D29),
    sectionBorder = Color(0x88B8914A),
    sectionShadow = 1.dp,
    row = Color(0xFF0D131C),
    rowBorder = Color(0x66C8A45A),
    input = Color(0xFF0D131C),
    inputBorder = Color(0x77B8914A),
    inputBorderFocused = Color(0xCCE5C16A),
    divider = Color(0x55B8914A),
    textPrimary = Color(0xFFF3F0E8),
    textSecondary = Color(0xFFBDAF8A),
    textMuted = Color(0xFF7E8490),
    goldAccent = Color(0xFFE5C16A),
    goldHighlight = Color(0x99FFE39B),
    avatarBg = Color(0xFF1A2230),
    avatarBorder = Color(0xB8E5C16A),
    success = Color(0xFF8CCF91),
    warning = Color(0xFFE6A84A),
    error = Color(0xFFE06F70),
    disabled = Color(0xFF6D7480),
    leftPanelStart = Color(0xFF182232),
    leftPanelEnd = Color(0xFF0A0E16),
    iconTile = Color(0x332B3A52),
    subtleGlow = Color(0x33E5C16A),
    baopeiRow = Color(0x3DE06F70),
    baopeiBorder = Color(0x99E06F70),
    baopeiTag = Color(0x2FE06F70),
    rankSilver = Color(0xFFC0C8D5),
    rankBronze = Color(0xFFD28A4A),
    button = ChuButtonPalette(
        primaryGradient = listOf(Color(0xFFE5C16A), Color(0xFFC59A45), Color(0xFF8E6727)),
        primaryBorder = Color(0x99FFE39B),
        secondaryBg = Color(0xFF151D29),
        secondaryBorder = Color(0x88B8914A),
        ghostBg = Color(0x33151D29),
        ghostBorder = Color(0x66B8914A),
        dangerBg = Color(0x88271014),
        dangerBorder = Color(0x99E06F70),
        textPrimary = Color(0xFFFBF5E7),
        textSecondary = Color(0xFFE1D1A5),
        textDisabled = Color(0xFF6D7480),
        primaryShadow = 2.dp,
        secondaryShadow = 1.dp,
        ghostShadow = 0.dp,
        dangerShadow = 1.dp,
    ),
)

val LocalChuUiPalette = staticCompositionLocalOf { ClassicChuUiPalette }
